## MAIN CONFIGURATIONS
layouts:
    - fullscreen
    - tall
    - column

# Mouse will follow focus
mouse-follows-focus: true
focus-follows-mouse: false

# Add 15px margin between windows
window-margins: true
window-margin-size: 15

## CUSTOM MAPPINGS

# Modifier keys
mod1:
    - control
    - option
mod2:
    - control
    - option
    - command
    - shift

# Other mappings

cycle-layout:
    mod: mod1
    key: space
cycle-layout-backward:
    mod: mod2
    key: space

shrink-main:
    mod: mod1
    key: h
expand-main:
    mod: mod1
    key: l

focus-ccw:
    mod: mod1
    key: j
focus-cw:
    mod: mod1
    key: k
focus-main:
    mod: mod1
    key: m

swap-ccw:
    mod: mod2
    key: j
swap-cw:
    mod: mod2
    key: k
swap-main:
    mod: mod2
    key: m

throw-space-1:
    mod: mod1
    key: 1
throw-space-2:
    mod: mod1
    key: 2
throw-space-3:
    mod: mod1
    key: 3
throw-space-4:
    mod: mod1
    key: 4
throw-space-5:
    mod: mod1
    key: 5
throw-space-6:
    mod: mod1
    key: 6
throw-space-7:
    mod: mod1
    key: 7

throw-screen-1:
    mod: mod2
    key: 1
throw-screen-2:
    mod: mod2
    key: 2

focus-screen-1:
    mod: mod2
    key: 3
focus-screen-2:
    mod: mod2
    key: 4

toggle-float:
    mod: mod2
    key: f

display-current-layout:
    mod: mod1
    key: i

reevaluate-windows:
    mod: mod2
    key: z
relaunch-amethyst:
    mod: mod2
    key: x

